name: Build Version

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "The flutter repository branch name"
        default: "stable"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build \
            -t leobastiani/flutter:${{ inputs.branch_name }} \
            --build-arg=flutterVersion=${{ inputs.branch_name }} \
            --cache-from=type=registry,ref=leobastiani/flutter-cache:${{ inputs.branch_name }} \
            --cache-to=type=registry,ref=leobastiani/flutter-cache:${{ inputs.branch_name }},mode=max \
            --push \
            --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
            .
      - name: Build and push sudo image
        run: |
          docker build \
            -t leobastiani/flutter-sudo:${{ inputs.branch_name }} \
            --build-arg=flutterVersion=${{ inputs.branch_name }} \
            --push \
            --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
            -f Dockerfile.sudo \
            .
